name: Build core binaries for Linux

on:
  push:
    branches: [ "build-test" ]  # Trigger only on the specific branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
